{{ if .Values.clickhouse.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uptrace-clickhouse
  labels:
    app: clickhouse
    {{- include "uptrace.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.clickhouse.replicaCount }}
  serviceName: uptrace-clickhouse
  selector:
    matchLabels:
      app: clickhouse
      {{- include "uptrace.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: clickhouse
        {{- include "uptrace.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.clickhouse.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create -}}
      serviceAccountName: {{ include "uptrace.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.clickhouse.image.repository }}:{{ .Values.clickhouse.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.clickhouse.image.pullPolicy }}
          env:
            - name: CLICKHOUSE_DB
              value: uptrace
          {{- if .Values.clickhouse.persistence.enabled }}
          volumeMounts:
          - name: uptrace-clickhouse-data
            mountPath: /var/lib/clickhouse
          {{- else }}
          volumeMounts: []
          {{- end }}
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
            - name: tcp
              containerPort: 9000
              protocol: TCP
          # NOTE: This may fail on intranet clusters
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.clickhouse.resources | nindent 12 }}
      {{- with .Values.clickhouse.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.clickhouse.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.clickhouse.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes: []
{{ if .Values.clickhouse.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: uptrace-clickhouse-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if not (eq .Values.clickhouse.persistence.storageClassName "") }}
      storageClassName: {{ .Values.clickhouse.persistence.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.clickhouse.persistence.size }}
{{ end }}
{{ end }}
